- references/cli.md
- substra/cli/interface.py
- substra/runner.py
- tests/__init__.py
- tests/sdk/__init__.py
- tests/test_runner.py
The run-local command currently only accepts directories for the ALGO arg and --metrics option. This prevents user from testing that their archives are indeed valid.
With this PR, users can now pass either folders or archive paths to these 2 parameters.
> Accept algo/metrics archives in run-local

- tests/sdk/test_describe.py
- tests/sdk/test_download.py
- tests/sdk/test_leaderboard.py
The license is missing in the following files:
• tests/sdk/test_describe.py
• tests/sdk/test_download.py
• tests/sdk/test_leaderboard.py
> Add licenses on tests

- tests/test_cli.py
When writing tests for the CLI, it is hard to understand why the command
could fail because the output is not printed in the tests output.
When the exit_code is not the one expected, the command output will be
printed to the tests output.
> improve debugging when writing CLI tests

- docs/local_install.md
- examples/compute_plan/assets/algo_sgd/Dockerfile
- examples/titanic/assets/algo_constant/Dockerfile
- examples/titanic/assets/algo_random_forest/Dockerfile
- examples/titanic/assets/objective/Dockerfile
Since our docker images are now available on the public docker registry, the references to our private one are irrelevant. This PR replaces them with the new public ones.
Also, the MacOS Catalina update forced us to update the default working dir of the substra platform in `/tmp/substra`, I updated the guide accordingly.
> Remove reference to private docker registry

- tests/sdk/test_rest_client.py
- tests/test_cli.py
- tests/test_runner.py
Since the last release of pytest-mock, mocker.patch isn't compatible with context managers anymore : https://github.com/pytest-dev/pytest-mock#note-about-usage-as-context-manager
This made the tests in test_runner.py fail.
This PR updates them to follow the proper usage of mocker.
See also https://github.com/pytest-dev/pytest-mock/releases/tag/v1.12.0
> Update usage of mocker

- references/cli.md
- references/sdk.md
- substra/cli/interface.py
- substra/cli/printers.py
- substra/sdk/client.py
- tests/datastore.py
- tests/sdk/test_get.py
- tests/sdk/test_list.py
- tests/test_cli.py
* Allow get and list for compute_plans.
* Add "add compute_plan" command to the CLI (previously only available in SDK)
This PR depends on https://github.com/SubstraFoundation/substra-backend/pull/34
While ensuring that the new commands were tested, I realized that the 409 errors in the cli were only tested for datasets. I updated the test so that all assets are tested.
> get and list compute_plans

- references/cli.md
- references/sdk.md
- substra/cli/interface.py
- substra/cli/printers.py
- substra/sdk/client.py
- tests/test_cli.py
- tests/test_runner.py
* Adds composite_traintuples and aggregatetuples to the structure of a compute plan
* Removes the global `algo_key` option of the `add compute_plan` command and moves it to the contents of each tuple
* Fixes a typo in test_runner.py
> Generic compute plan

- substra/sdk/client.py
Currently, when an asset is added, a `permissions` field is automatically created, even if the asset doesn't needs one (for example, `traintuple` or `testtuple`).
This PR aims to avoid adding a default permissions field for these assets.
Issue related to this PR: #19
> Adding asset without permissions field - Issue #19

- references/cli.md
- substra/cli/interface.py
- tests/test_cli.py
As written in the following comment:
```
```
> Group config, profile, user & verbose options in a global decorator

- substra/cli/interface.py
As specified in this issue (#59), it could be good to rename the `leaderboard` variable in `substra/cli/interface.py::leaderboard`, because it's already defined before and may cause issues.
🔗 Related issue: #59
> Rename leaderboard variable in substra/cli/interface.py::leaderboard

- references/sdk.md
- substra/sdk/client.py
This issue has been reported by @camillemarini and @jmorel.
It has been also fixed in the PR #52 that is currently under review. 
For bug fixes we should try to create independent PRs. It will allow to review them faster and then to merge them faster.
> doc: add missing rank attribute for add_traintuple method

- examples/compute_plan/scripts/add_compute_plan.py
- examples/cross_val/scripts/cross_val_algo_random_forest.py
- examples/titanic/scripts/add_train_algo_constant.py
- examples/titanic/scripts/add_train_algo_random_forest.py
- references/cli.md
- references/sdk.md
- substra/cli/interface.py
- substra/cli/printers.py
- substra/sdk/client.py
- tests/test_cli.py
Companion PR: [backend](https://github.com/SubstraFoundation/substra-backend/pull/63)
- Removes the objective key from traintuples, aggregatetuples, composite traintuples and compute plans.
- Requires objective key in testtuples.
- Misc fixes regarding the printers following the structure change (adding rank everywhere, removing perf from train like tuples)
> Fail fast: remove evaluation for train like tuples

- references/cli.md
- references/sdk.md
- substra/cli/interface.py
- substra/cli/printers.py
- substra/sdk/client.py
- tests/sdk/test_cancel.py
- tests/test_cli.py
In link with the "fail fast" mission, we need to have in both the CLI and SDK cancel compute plan commands / methods.
🔗 Related issue: #55 
Companion PR:
- [tests](https://github.com/SubstraFoundation/substra-tests/pull/26)
- [backend](https://github.com/SubstraFoundation/substra-backend/pull/65)
- [chaincode](https://github.com/SubstraFoundation/substra-chaincode/pull/53)
- [frontend](https://github.com/SubstraFoundation/substra-frontend/pull/33)
> New cancel compute_plan command

- substra/cli/interface.py
Currently, when the `keys` attribute is missing in the data_samples file we try to use, an error is raised and a full traceback is returned.
The commands impacted are the followings:
- add_objective
- add_traintuple
- add_composite_traintuple
- add_testtuple
- update_data_sample
🔗 Related issue: #50
> Avoid KeyError when keys are missing in the data_samples file

- README.md
- docs/README.md
- docs/concepts.md
- docs/full_pipeline_workflow.md
Following the move to github flow, all links pointing to the dev branch were broken.
> Fix links to substra-tools doc

- tests/test_cli.py
As specified in the related issue, this is sometimes hard to debug the CLI.
It could be good to add some information when a test crashes.
For instance, the full traceback, the exc_code, etc.
🔗 Related issue: #58
> Add debug for CLI's tests

- substra/sdk/exceptions.py
- substra/sdk/rest_client.py
- substra/sdk/utils.py
This PR aims to be resilient to backend bad gateway errors, that could happen if server is restarting or down for a short time.
Having a retry mechanism will allow not stoping the current script if the server is temporarily unavailable.
> add server gateway (bad, timout, unavailable) errors support and retry

- substra/sdk/client.py
- substra/sdk/rest_client.py
- add error instead of success when logging sdk method calls
- add key / asset name when retrying after a timeout
> Retry better logs

- tests/sdk/test_add.py
- tests/sdk/test_cancel.py
- tests/sdk/test_describe.py
- tests/sdk/test_download.py
- tests/sdk/test_get.py
- tests/sdk/test_leaderboard.py
- tests/sdk/test_list.py
- tests/sdk/test_update.py
- tests/test_cli.py
🔗 Related issue: #83 
Currently, when using `is_called()` in the tests, the assert is always passing, even when it shouldn't.
As an example (provided in the issue), this test is passing but should not :
```python
def test_foo(mocker):
m = mock_requests(mocker, "post", response='foo')
assert m.is_called()
```
When checking the documentation of unittest.mock (https://docs.python.org/3/library/unittest.mock.html), it looks like this method doesn't exists at all.
I think we should use `assert_called()`, which is the assert we actually wanted.
> Replace is_called() by assert_called() in tests

- substra/sdk/rest_client.py
- tests/sdk/test_describe.py
- tests/sdk/test_download.py
- tests/sdk/test_rest_client.py
- tests/sdk/utils.py
This is required as we don't know on a ledger timeout error if the request will be processed by the chaincode.
> Change retry strategy on post request on ledger timeout

- substra/cli/printers.py
Since the compute plan now contains doneCount and tupleCount properties, we can display the overall progress to the user.
> Display compute plan progress in CLI

- substra/cli/printers.py
Add to the traintuple, composite traintuple and aggregatuple printers a command to list all related testtuples.
> Update tuple printers with command to list testtuples

- substra/cli/interface.py
The repo name is still "substra-cli" instead of "substra" in the `substra --help` command.
> Update repo name in substra --help

- tests/sdk/test_config.py
🔗 **Related PRs**:
- [Fix rest client login headers](https://github.com/SubstraFoundation/substra/pull/106)
- [Update examples with headers fix in rest_client](https://github.com/SubstraFoundation/substra/pull/108)
This PR aims to update the tests with the fixed headers in the rest client.
> Update tests with headers fix in rest_client

- README.md
This is a first attempt at having a central place where we can document which versions are compatible with each other.
Sometimes, as a dev, it's useful to have a working baseline that "we know works".
It can also be useful in deployment scenarios to document tested releases.
> Compatibility table

- references/cli.md
- references/sdk.md
- substra/cli/interface.py
- substra/sdk/client.py
🔗 **Related issue:** #112 
When using the `substra add compute_plan --help` command, the JSON file schema provided is the following:
```json
{
"traintuples": list[{
"algo_key": str,
"data_manager_key": str,
"train_data_sample_keys": list[str],
"traintuple_id": str,
"in_models_ids": list[str],
"tag": str,
}],
"composite_traintuples": list[{
"algo_key": str,
"data_manager_key": str,
"train_data_sample_keys": list[str],
"in_head_model_id": str,
"in_trunk_model_id": str,
"out_trunk_model_permissions": {
"authorized_ids": list[str],
},
"tag": str,
}]
"aggregatetuples": list[{
"algo_key": str,
"worker": str,
"in_models_ids": list[str],
"tag": str,
}],
"testtuples": list[{
"objective_key": str,
"data_manager_key": str,
"test_data_sample_keys": list[str],
"testtuple_id": str,
"traintuple_id": …
```
> Update compute plan's documentation

- references/cli.md
- references/sdk.md
- substra/cli/interface.py
- substra/cli/printers.py
- substra/sdk/client.py
- tests/datastore.py
- tests/sdk/test_update.py
- New sdk method: `update_compute_plan`
- New CLI asset (`compute_plan`) for command `update`
Companion PRs:
* https://github.com/SubstraFoundation/substra-backend/pull/137
* https://github.com/SubstraFoundation/substra-tests/pull/69
* https://github.com/SubstraFoundation/substra-chaincode/pull/89
> Update compute plan

- examples/compute_plan/scripts/add_compute_plan.py
- examples/compute_plan/scripts/display_scores.py
- examples/config.json
- examples/cross_val/scripts/cross_val_algo_random_forest.py
- examples/titanic/README.md
- examples/titanic/scripts/add_dataset_objective.py
- examples/titanic/scripts/add_train_algo_constant.py
- examples/titanic/scripts/add_train_algo_random_forest.py
🔗 **Related PRs**:
- [Fix rest client login headers](https://github.com/SubstraFoundation/substra/pull/106)
- [Update tests with headers fix in rest_client](https://github.com/SubstraFoundation/substra/pull/109)
We are currently modifying the way the login headers works in #106. We are removing the config.json (where the password is set) and storing its content through the headers instead.
This PR has been opened in order to apply these changes in the examples we can find on the `substra` repository.
We are just replacing this:
```py
client = substra.Client()
client.add_profile(config['profile_name'], config['username'], config['password'],  config['url'])
client.login()
``` 
by this:
```py
client = substra.Client(profile_name="node-1")
client.login()
```
> Update examples with headers fix in rest_client

- substra/sdk/exceptions.py
- substra/sdk/rest_client.py
resolve #75 
The documentation part of this issue is covered by https://github.com/SubstraFoundation/substra/pull/110.
> Add clear error message when sdk can't fetch from keyring

- substra/sdk/client.py
#121 shows that profile name was not correctly set (triggers in substra-tests)
> Fix profile name set missing

- references/cli.md
- substra/cli/interface.py
Currently, when using the following command, the type of the `--algo-key` option isn't specified: 
```sh
substra add aggregatetuple --help
```
Maybe we could add this information in order to make this doc easier to understand?
> Add algo type in add aggregatetuple

- substra/cli/printers.py
Adds the "tag" field to the list and detail mode of ComputePlanPrinter.
> Add tag to compute plan printer

- substra/sdk/config.py
- tests/sdk/test_config.py
- tests/test_cli.py
**🔗 This PR is related to the following issue: #117**
As specified in the issue, we get a `FileNotFoundError` when the config file specified in our command doesn't exists.
The goal of this PR is to be able to return instead a `ConfigException` that describes the error.
_The first two examples of the **With or without a .substra file** part have already been fixed in another PR._
> Handle FileNotFoundError when config file not found (WIP)

- substra/cli/interface.py
- substra/runner.py
Filenames should be validated when storing asset to prevent from path/directory traversal.
Companion PR :  https://github.com/SubstraFoundation/substra-backend/pull/192
> Prevent from path traversal when extracting archives

- examples/titanic/.gitignore
- examples/titanic/README.md
The commands from the `Using asset command line interfaces` section assumed there was a prediction after each train, which there isn't anymore. I added the predict command and fixed the local of all output files.
> Fix titanic readme following removal of auto eval

- Makefile
- references/sdk.md
- substra/sdk/client.py
This branch adds documentation to `add_` methods in the client specifying when the `AlreadyExists` exception are raised.
To make the generation of documentation a bit faster when testing, I to the makefile two new targets: `doc-cli` and `doc-sdk`.
Fixes #92
> Document when AlreadyExists exception are raised

- references/cli.md
- references/sdk.md
- substra/cli/interface.py
- substra/sdk/client.py
- substra/sdk/rest_client.py
The is_complex option that the backend exposes for debug purposes was described in both CLI and SDK but never passed to the backend. This PR removes it to make our public interfaces cleaner.
> Remove is_complex option

- substra/sdk/rest_client.py
Fixes #164 
When retrying to send files to the backend, we used the same file-like object without making sure that the offset was 0. As a result, all retries tried to send empty objects.
> Rewing files before uploading

- .travis.yml
- substra/cli/interface.py
Release of flake8 3.8.0 is triggering a new warning in our code base. 
This PR is fixing it to keep using the latest version of flake8.
> Fix ci (new release of flake8)

- docs/local_install_skaffold.md
Add `helm repo add` which is necessary since https://github.com/SubstraFoundation/substra-backend/pull/260.
See also: https://github.com/SubstraFoundation/substra-tests/pull/110
> add `helm add repo bitnami`

- examples/compute_plan/scripts/add_compute_plan.py
- examples/compute_plan/scripts/display_scores.py
- examples/cross_val/scripts/cross_val_algo_random_forest.py
- examples/titanic/scripts/add_dataset_objective.py
- examples/titanic/scripts/add_train_algo_constant.py
- examples/titanic/scripts/add_train_algo_random_forest.py
In the examples, we tell the user to login manually through the readme and then login again in each script. These subsequent logins have for consequence to invalidate the token obtained in the first manual login.
This PR removes these unnecessary logins.
> Remove logins from examples

- substra/sdk/exceptions.py
Fixes #35 
This make traceback go from:
```sh
➜ python test.py
Traceback (most recent call last):
File "/Users/jeremy/substra/substra/substra/sdk/rest_client.py", line 126, in __request
r.raise_for_status()
File "/Users/jeremy/.virtualenvs/substra/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://substra-backend.node-1.com/data_manager/
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "test.py", line 42, in <module>
dataset_key = client.add_dataset(DATASET, exist_ok=True)['pkhash']
File "/Users/jeremy/substra/substra/substra/sdk/client.py", line 41, in wrapper
return f(*args, …
```
> Improve error messages in tracebacks

- substra/cli/interface.py
- substra/sdk/exceptions.py
Fixes #147
Validation errors will be displayed as:
```sh
➜ substra add  dataset dataset.json
Error: Could not add dataset, the server returned the following errors:
- type: This field may not be null.
- permissions: This field may not be null.
```
> Nice display for validation errors in cli

- docs/local_install_skaffold.md
- examples/titanic/README.md
- references/cli.md
- references/sdk.md
- setup.py
- substra/cli/interface.py
- substra/sdk/client.py
- substra/sdk/config.py
- substra/sdk/exceptions.py
- substra/sdk/rest_client.py
- tests/sdk/conftest.py
- tests/sdk/test_config.py
- tests/sdk/test_rest_client.py
- tests/test_cli.py
This PR removes the storage of user passwords in the keyring. 
The client can now be initialized with an existing token or will use the one from `~/.substra-user`.
- removed `--username` and `--password` options from the `config` command
- added `--username` and `--password` options to the `login` command. If not provided at call, the command will prompt the user for values and the password won't be displayed at all.
- the `Client` constructor takes an optional `token` arg instead of the previous `username` and `password`
- `add_profile` doesn't have `username` and `password` anymore
- new `set_token` method
Since this introduces a change in our public interface, there are a few companion PRs:
* substra-backend: https://github.com/SubstraFoundation/substra-backend/pull/202
* …
> Remove use of keyring

- references/cli.md
- references/sdk.md
- substra/cli/interface.py
- substra/sdk/client.py
:link: **Related Pull Requests :**
• [substra-tests](https://github.com/SubstraFoundation/substra-tests/pull/112)
• [substra-chaincode](https://github.com/SubstraFoundation/substra-chaincode/pull/121)
• [substra-backend](https://github.com/SubstraFoundation/substra-backend/pull/273)
This PR aims to add a metadata field to the compute plan asset.
> Add metadata to compute_plan

- substra/sdk/backends/local/backend.py
- substra/sdk/backends/local/compute/worker.py
- substra/sdk/backends/local/db.py
- substra/sdk/backends/local/models.py
- substra/sdk/schemas.py
- Substra sdk, local backend: add the functions `add_composite_traintuple`, `add_aggregate_traintuple`
- Substra sdk, schemas: update the pydantic typing: pathlib.Path accepts Path and str
- added checks on the metadata, this is not directly related to composite/aggregate but they need the checks too.
- each key in metadata can be of length 50 max
- each value in metadata can be of length 100 max and cannot be empty
> Local backend - add support for composite and aggregate traintuples

- substra/cli/interface.py
Fixes #210 
Errors returned by the backend can take multiple shape:
```json
{"message":[{"metrics":["Cannot handle this file object."]}],"pkhash":"dcb95dfc837ee32f3feaacdf3835fe350d625c47f48bc21aeda41bdcceea6c67"
```
```json
{"message":"error checking associated objective no asset for key foo"}
```
```json
{"permissions":["This field may not be null."]}
```
This update handle all 3 shapes.
> Fix error parsing in CLI

- references/cli.md
- substra/cli/interface.py
In the CLI, when
- adding a compute plan
- updating a compute plan
add the following options:
- disable the auto batching
- set the batch size
> feat: add options for auto batching in the CLI

- examples/compute_plan/scripts/add_compute_plan.py
- examples/cross_val/scripts/cross_val_algo_random_forest.py
- examples/debugging/scripts/debugging.py
- examples/debugging/scripts/local_debugging.py
- examples/titanic/scripts/add_dataset_objective.py
- examples/titanic/scripts/add_train_algo_constant.py
- examples/titanic/scripts/add_train_algo_random_forest.py
- substra/sdk/backends/local/backend.py
- substra/sdk/backends/local/models.py
- substra/sdk/backends/remote/backend.py
- substra/sdk/backends/remote/rest_client.py
- substra/sdk/exceptions.py
- tests/datastore.py
- tests/sdk/test_add.py
- tests/sdk/test_rest_client.py
The goal of this multi-repo PRs is to make sure that all the asset creation endpoints returns only the "key" of the asset. 
Indeed, currently `create` and 'get' an asset return, respectively, `pkhash` and `key`. As `pkhash` is only a substra-backend concept, we need to move from `pkhash` to `key` when dealing with substra cli/sdk and frontend.
Consequently, when client create a new asset, the substra-backend will now only return the `key` of the created asset.
There is an exception for compute plan which need to be returned in its complete form because client need to get the ID_to_key mapping and it’s returned only when client create this asset.
The client will take care of doing an extra GET in order to retrieve the complete asset.
PRs : …
> Use key instead of pkhash

- substra/sdk/backends/local/backend.py
- substra/sdk/backends/local/dal.py
- substra/sdk/backends/local/db.py
In debug mode, when we create an asset, we first test if it exists
- Before: the asset does not exist, log an error 'asset does not exist'
- After: can deactivate this log so no error shown to the user when we create the asset
> Do not log "asset not found" at creation - debug mode

- .travis.yml
- Makefile
- README.md
- bin/generate_sdk_schemas_documentation.py
- examples/compute_plan/scripts/add_compute_plan.py
- examples/compute_plan/scripts/display_scores.py
- examples/debugging/scripts/debugging.py
- examples/debugging/scripts/local_debugging.py
- references/sdk.md
- references/sdk_models.md
- references/sdk_schemas.md
- substra/cli/interface.py
- substra/cli/printers.py
- substra/sdk/backends/local/backend.py
- substra/sdk/backends/local/compute/worker.py
- substra/sdk/backends/local/dal.py
- substra/sdk/backends/local/db.py
- substra/sdk/backends/remote/backend.py
- substra/sdk/client.py
- substra/sdk/exceptions.py
- substra/sdk/models.py
- substra/sdk/schemas.py
- substra/sdk/utils.py
- tests/datastore.py
- tests/sdk/test_add.py
- tests/sdk/test_cancel.py
- tests/sdk/test_get.py
- tests/sdk/test_list.py
- tests/sdk/test_update.py
- tests/test_cli.py
Substra SDK: return a Pydantic object instead of a dict
- fix:
Companion PR: https://github.com/SubstraFoundation/substra-tests/pull/144
> feat: return an actual object as output

- substra/sdk/backends/local/compute/worker.py
In debug mode, when connected to a deployed platform and creating a testtuple in local associated to a remote dataset, the script counts the number of test data samples in the testtuple and generates as many fake data samples.   
The bug is that instead of counting the number of samples for this testtuple, it counts the number of test data samples linked to the objective.  
It gives a false result if the testtuple uses other samples (as defined by the user) and throws an error if the objective has no test dataset.
- locally deploy Substra
- add a dataset
- add an objective with `test_dataset=None `
- in debug mode: add a testtuple associated to this objective and dataset
Modifying the 'test_debug.py::test_execution_debug' in substra-tests like this works too to reproduce:
```python
def …
```
> fix: debug mode - fix get the number of samples in testtuple

- references/sdk.md
- substra/sdk/backends/local/backend.py
- substra/sdk/backends/local/dal.py
- substra/sdk/client.py
- tests/sdk/test_debug.py
User feedback:
- Login from the SDK in the examples, instead of logging in from the CLI then use the SDK
- Expose the temporary directory in debug mode so that the user an pause the execution and check the assets
EDIT: only expose the temp dir following the discussions on the login
> feat: login from SDK in examples and expose temp dir in debug mode

- .travis.yml
- Makefile
- bin/generate_sdk_documentation.py
- references/sdk.md
- requirements.txt
- substra/sdk/client.py
- substra/sdk/utils.py
The previous way of generating the SDK doc meant that we had to change from the default Google docstring.
For example, this:
```python
def my_func():
"""Returns a new Client configured with profile data from configuration files.
Args:
profile_name (str, optional): Name of the profile to load.
Defaults to 'default'.
retry_timeout (int, optional): Number of seconds before attempting a retry call in case
of timeout. Defaults to 5 minutes.
Returns:
Client: The new client.
"""
```
Gave something like this: 
```
Returns a new Client configured with profile data from configuration files.
Args:
profile_name (str, optional): Name of the profile to load. Defaults to 'default'. retry_timeout (int, optional): Number of seconds before attempting a retry call in case of timeout. Defaults to 5 minutes. …
```
> Generate the documentation of the SDK - arguments as markdown instead of block quotes

- substra/sdk/backends/local/backend.py
- substra/sdk/backends/local/compute/spawner.py
- substra/sdk/backends/local/dal.py
This PR is for fixes for the example with MONAI
- debug mode - container use the host system’s IPC namespace, [see the comment](https://github.com/owkin/MONAI/pull/2#issuecomment-700778936)
- debug mode - more memory for the container
- debug mode - `list` function: try to call the remote if have an URL for it but may not be connected
> Fixes for the example with MONAI

- .gitignore
- examples/compute_plan/scripts/add_compute_plan.py
- references/cli.md
- references/sdk.md
- references/sdk_models.md
- references/sdk_schemas.md
- substra/cli/interface.py
- substra/cli/printers.py
- substra/runner.py
- substra/sdk/backends/base.py
- substra/sdk/backends/local/backend.py
- substra/sdk/backends/local/compute/worker.py
- substra/sdk/backends/local/db.py
- substra/sdk/backends/remote/backend.py
- substra/sdk/client.py
- substra/sdk/exceptions.py
- substra/sdk/models.py
- substra/sdk/schemas.py
- tests/datastore.py
- tests/test_cli.py
Follow-up to https://github.com/SubstraFoundation/substra/pull/235
Companion PRs:
- https://github.com/SubstraFoundation/substra-backend/pull/345
- https://github.com/SubstraFoundation/substra-chaincode/pull/129
- https://github.com/SubstraFoundation/substra-tests/pull/158
Rename:
| Before | After |
|---|----|
| `compute_plan_id` | `compute_plan_key` (or simply `key`) |
|  `hash` | `checksum` |
| `data_manager.keys` | `data_manager.data_sample_keys` |
> Rename a few attributes

- references/sdk.md
- substra/sdk/backends/local/backend.py
- substra/sdk/backends/local/compute/worker.py
- substra/sdk/backends/local/dal.py
- substra/sdk/backends/local/db.py
- substra/sdk/client.py
Enable chainkey support in debug mode. This needs the 'debug_multi_nodes' feature #238 
- init the local backend:
- env variables "CHAINKEYS_ENABLED" and "CHAINKEYS_DIR". I chose environment variables to avoid having extra variables specific to the debug mode in the Client initialization.
- Worker: get the chainkey that matches the `tuple_.dataset.worker`, and give the env variable "NODE_INDEX" to the Docker container for the task
- aggregate tuple that has a composite traintuple in its in models: it took the head instead of the trunk
- Compute plan - get id to rank: always tried to get a traintuple from the db, even if composite traintuple or aggregatetuple
- DB in debug mode: the db was always the same so if you create several clients in the same context, they share the db (caused …
> Enable chainkey support in debug mode

- references/sdk.md
- references/sdk_models.md
- substra/__init__.py
- substra/sdk/__init__.py
- substra/sdk/backends/local/backend.py
- substra/sdk/backends/local/compute/worker.py
- substra/sdk/backends/local/dal.py
- substra/sdk/backends/local/db.py
- substra/sdk/client.py
- substra/sdk/models.py
- tests/datastore.py
- tests/sdk/test_debug.py
In "normal" mode, the user connects to a node, adds the data on this node. When a DS creates a traintuple (or another task), it is executed where the data is: on the node of the dataset. To know which node a dataset is on, get the `dataset.owner` attribute.
The goal of this PR is to simulate this behaviour in debug mode.
- **What it does**: 
- for the [chainkey use case](https://github.com/SubstraFoundation/substra/pull/239/files), get the appropriate chainkey for each tuple. So with this other PR, the public feature 'support chainkeys' is added to the debug mode.
- **What it does not do**: there is no check on the permissions in debug mode, so impossible to test them with this (but they are computed so the user can display them)
In debug mode, the user can assign a specific node as the …
> Add support for 'multi nodes' to the debug mode

- substra/sdk/backends/local/compute/spawner.py
- substra/sdk/backends/local/compute/worker.py
- substra/sdk/schemas.py
- tests/sdk/conftest.py
- tests/sdk/data_factory.py
- tests/sdk/test_debug.py
In a 'real' setup, when executing a compute plan on several nodes, there is a local folder for the compute plan on each node, shared by all tasks of the CP that are executed on that node.
- In debug mode, there was one folder per compute plan. This MR makes it so that there is one shared folder per compute plan per node.
- Also added a factory to test the debug mode without substra-tests.
- Fixed TraintupleSpec `from_compute_plan` method in case `in_models_ids` is None
> Debug mode - multi nodes - create one local folder per node per compute plan

- substra/sdk/client.py
- tests/sdk/test_update.py
Call the client function `update_compute_plan` with `data` of type schemas.UpdateComputePlanSpec fails.  
trying with `data` of type dict works
Fixed the bug and added a test
> Fix update CP with schema as input

- references/cli.md
- references/sdk.md
- substra/cli/interface.py
- substra/cli/printers.py
- substra/sdk/backends/local/backend.py
- substra/sdk/backends/local/compute/worker.py
- substra/sdk/backends/local/dal.py
- substra/sdk/backends/remote/backend.py
- substra/sdk/backends/remote/rest_client.py
- substra/sdk/client.py
- substra/sdk/exceptions.py
- substra/sdk/models.py
- tests/datastore.py
- tests/sdk/test_download.py
- tests/test_cli.py
Companion PRs:
- https://github.com/SubstraFoundation/substra-tests/pull/182
- https://github.com/SubstraFoundation/substra-chaincode/pull/141
- https://github.com/SubstraFoundation/substra-backend/pull/395
--- 
This PR adds the new CLI commands
```sh
substra node info
substra download_model <MODEL_KEY>
substra download_model --from-traintuple <TUPLE_KEY>
substra download_model --from-aggregatetuple <TUPLE_KEY>
substra download_model --from-composite-head <TUPLE_KEY>
substra download_model --from-composite-trunk <TUPLE_KEY>
```
and the respective SDK functions 
```python
node_info(self) -> str
download_model(self, key: str, folder) -> None
download_traintuple_model(self, tuple_key: str, folder) -> None
download_aggregatetuple_model(self, tuple_key: str, folder) -> None …
```
> feat: export model + node info

- substra/sdk/backends/local/backend.py
- substra/sdk/backends/local/compute/__init__.py
- substra/sdk/backends/local/compute/worker.py
In debug mode, when the chainkeys are enabled, they are created in `~/.substra_chainkeys`
What this PR changes:
- the folder `~/.substra_chainkeys` is now `local-worker/chainkeys`
That way, in debug mode everything is created inside the `local-worker` directory.
> debug: move the chainkeys to local-worker

- substra/sdk/backends/local/backend.py
- substra/sdk/schemas.py
- tests/sdk/test_debug.py
Debug mode - bug fix
This is a bug fix on the update of a compute plan after having added other tuples by setting their compute plan key. The code of the error is similar to this:
```python
cp = client.create_compute_plan(...)
client.add_traintuple({compute_plan_key = cp.key, ...})
traintuple_specs = ... # specs of type substra.schemas.Type.ComputePlanTraintupleSpec, no in models
client.update_compute_plan({'traintuples': traintuple_specs})
```
(created a test to reproduce it)
In the `update_compute_plan` function, for each tuple, in their in_model_ids, **ids and keys** are accepted.  
Ids can be the ids assets added during the same call or in a previous call to `update_compute_plan` (there are tests in substra-tests that expect this behaviour).   
That means that we need to save the …
> debug mode - fix update CP after an add

- CHANGELOG.md
- references/sdk.md
- substra/sdk/backends/local/compute/worker.py
- substra/sdk/client.py
- substra/sdk/models.py
- tests/sdk/test_list.py
Add an endpoint in order to be able to list models and filter the list by compute task key to retrieve the models produced by a task. It is needed because I don't want to use the field `task.<category>.models` as it will be removed soon.
> feat: add an endpoint to list models

- tests/data_factory.py
- tests/fl_interface.py
Companion PRs: 
- substra tools: https://github.com/Substra/substra-tools/pull/49 (main)
- substra-test: https://github.com/Substra/substra-tests/pull/200
- substra: https://github.com/Substra/substra/pull/278 (here)
e2e tests: https://github.com/owkin/connect-ci/actions/runs/3051066299/jobs/4918859354
there is an inconsistency between the declared input for predict task and the one generated per connect-tools.
As substra-tools consumes the inputs and outputs with the companion RP, I added the fix to this batch.
The other solution would have been to do a separate batch to fix this issue in addition (longer and useless IMO).
About how to run the tests please check substra-tools companion PR
> tests: fix algo inputs and task code consistency

- CHANGELOG.md
- substra/sdk/backends/local/backend.py
- substra/sdk/models.py
- substra/sdk/schemas.py
- tests/data_factory.py
- tests/sdk/local/test_debug.py
The `clean_models` is now removed as users should use the `transient` flag on tasks outputs instead.
> chore!: remove clean_models flag on compute plans

- CHANGELOG.md
- references/sdk_models.md
- references/sdk_schemas.md
- substra/sdk/backends/local/backend.py
Do not rely on Algo categories for validation since they are deprecated.
Related:
- https://github.com/Substra/orchestrator/pull/24
- https://github.com/Substra/substra-backend/pull/460
> feat: stop checking algo category

- CHANGELOG.md
- Makefile
- references/sdk.md
- substra/__init__.py
- substra/sdk/__init__.py
- substra/sdk/backends/__init__.py
- substra/sdk/backends/base.py
- substra/sdk/backends/local/backend.py
- substra/sdk/backends/local/compute/spawner/__init__.py
- substra/sdk/backends/remote/backend.py
- substra/sdk/client.py
- substra/sdk/config.py
- substra/sdk/schemas.py
- tests/sdk/local/conftest.py
- tests/sdk/local/test_debug.py
https://github.com/Substra/substra/pull/287
https://github.com/Substra/substrafl/pull/19
https://github.com/Substra/substra-tests/pull/210
https://github.com/Substra/substra-documentation/pull/178
In local mode, we can choose between docker model and subprocess mode. This choice is done by the user by specifying an environment variable.
Specifying an environment variable can be difficult and annoying for the user, especially for user without a lof of experience with the terminal.
Specify the local mode with: Client(mode=["REMOTE", "LOCAL_DOCKER", "LOCAL_SUBPROCESS"])
default value: remote
right now there is a variable env, change how it is passed
use an enum
update the tests:
substra
connectlib
connect-tests
update the examples:
connect-documentation
update the CI
Tests: parametrize the …
> feat!: set the mode directly in the client 

- CHANGELOG.md
- references/sdk_schemas.md
- substra/sdk/backends/local/backend.py
- substra/sdk/schemas.py
- tests/sdk/local/test_debug.py
See [PR description](https://github.com/Substra/substra-backend/pull/468) for more details
The remote backend prevents now the use of `__` in asset metadata keys, to keep filtering feature on metadata fully functionnal.
Even though it's not an issue in local mode, allowing different naming in local and remote mode should be avoided, this PR prevents use of `__` in asset metadata keys in local mode as well.
Companion PR : 
- https://github.com/Substra/substra-backend/pull/468
> feat: prevent use of '__' in asset metadata keys in local mode

- CHANGELOG.md
- substra/sdk/backends/local/compute/spawner/base.py
- substra/sdk/backends/local/compute/spawner/docker.py
Companion PRs:
- https://github.com/Substra/substra-backend/pull/483 (main PR)
- https://github.com/Substra/orchestrator/pull/38
- https://github.com/Substra/substra/pull/295 (this PR)
- https://github.com/Substra/substra-tests/pull/218
- https://github.com/Substra/substra-frontend/pull/116
- https://github.com/Substra/substra-documentation/pull/184
---
> feat: docker: add build logs to container image build exception messages

- CHANGELOG.md
- references/sdk_models.md
- references/sdk_schemas.md
- substra/sdk/backends/local/backend.py
- substra/sdk/models.py
- substra/sdk/schemas.py
- tests/conftest.py
- tests/data_factory.py
- tests/fl_interface.py
- tests/sdk/local/test_debug.py
Signed-off-by: Louis Hulot <louis.hulot@owkin.com>
Companion PRs:
substra-tests: https://github.com/Substra/substra-tests/pull/219 
substrafl: https://github.com/Substra/substrafl/pull/29
substra: https://github.com/Substra/substra/pull/294 (main) (here)
documentation: https://github.com/Substra/substra-documentation/pull/186
orchestrator: https://github.com/Substra/orchestrator/pull/42
backend: https://github.com/Substra/substra-backend/pull/487 
Remove AlgoCategory from substra. 
As the test are based on AlgoCategory I put the class within the fl_interface
> remove: algo category from schemas and models

- CHANGELOG.md
- references/cli.md
- substra/sdk/backends/base.py
- substra/sdk/backends/local/backend.py
- substra/sdk/backends/remote/backend.py
There was a return statement missing. While I was there, I added type hints.
If accepted, this fix should be backported to the 0.38.x release.
> fix: return value of link_dataset_with_data_samples in remote mode

- README.md
Add new documentation URL and new Slack URL
Signed-off-by: Romain Goussault <romain.goussault@owkin.com>
> docs: Add new documentation URL and new Slack URL

- CHANGELOG.md
- references/sdk.md
- substra/sdk/backends/local/compute/spawner/subprocess.py
- tests/data_factory.py
- tests/sdk/local/test_debug.py
- tests/sdk/test_subprocess.py
- tests/test_cli.py
Companion PR:
- MAIN: https://github.com/Substra/substra-tools/pull/63
- https://github.com/Substra/substra/pull/303
- https://github.com/Substra/substrafl/pull/34
- https://github.com/Substra/substra-documentation/pull/201
- https://github.com/Substra/substra-tests/pull/224
> test: algo to function in substratools

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yaml
Signed-off-by: SdgJlbl <sarah.diot-girard@owkin.com>
https://app.asana.com/0/1203124674173179/1203854905218734/f
Add templates for Github issues
> chore: add issue templates

- CHANGELOG.md
- substra/sdk/backends/local/dal.py
- substra/sdk/backends/remote/backend.py
- substra/sdk/models.py
Signed-off-by: Milouu <milan.roustan@owkin.com>
Rename some fields of performances model to follow generic task naming
> chore: rename fields in Performances model

- README.md
[Pypi README](https://pypi.org/project/substra/) did not have the Substra logo image.
This PR should solve this.
This is based on this [stackoverflow thread](https://stackoverflow.com/questions/41983209/how-do-i-add-images-to-a-pypi-readme-that-works-on-github).
> docs: update readme image URL for Pypi readme

- CHANGELOG.md
- substra/sdk/backends/local/backend.py
- tests/sdk/local/test_debug.py
> fix: permissions inconsistency in local mode

- CHANGELOG.md
- references/sdk_models.md
- substra/sdk/models.py
Signed-off-by: Serge Bouchut <serge.bouchut@owkin.com>
Remove failed task category deprecated field.
See: https://github.com/Substra/substra-backend/pull/525
> feat: remove failed task category

- CHANGELOG.md
- bin/generate_cli_documentation.py
- bin/generate_sdk_schemas_documentation.py
- references/sdk.md
- references/sdk_models.md
- setup.py
- substra/sdk/client.py
- substra/sdk/exceptions.py
- tests/conftest.py
- tests/sdk/local/test_debug.py
- tests/sdk/test_archive.py
- tests/sdk/test_client.py
- tests/sdk/test_config.py
- tests/sdk/test_rest_client.py
This PR add the option to configure a Substra client using a configuration file or environment variables. 
The priority order is values given in code (override everything else) > values in environment variables > values in configuration file > default values. 
If both a token and a pair username / password are provided (by any means), the token will always be used. If a token is not provided, one will be generated from the username / password if appropriate (remote or hybrid client). 
It is also possible to regenerate a token by an explicit call to the `login` method.
This PR can be reviewed commit by commit.
It's a breaking change because the default (client instantiated with no parameter) will be a local subprocess client instead of a remote client. This decision was taken because the …
> feat!: client configuration with environment variables or configuration files

- CHANGELOG.md
- substra/sdk/backends/local/dal.py
- substra/sdk/backends/remote/backend.py
- substra/sdk/models.py
- tests/datastore.py
Performance asset were unique regarding their compute task key, and the function key they were computed from. Or, we want to have the possibility to have a function that outputs several performance and store them in the same task.
This implies two main things:
- Performance are now unique regarding the compute task key, the function key AND the output identifier
- The frontend must serialize regarding the identifier, and not the function key
The PR batch modify both the orchestrator and backend db in order to include the identifier as an additional unique condition.
In the backend, we use the ComputeTaskOutput as primary key directly.
- https://github.com/Substra/substra-backend/pull/634
- https://github.com/Substra/substra-tests/pull/251 (main)
- …
> chore: update performance view

- .pre-commit-config.yaml
- CHANGELOG.md
- substra/sdk/backends/local/backend.py
- substra/sdk/backends/local/compute/worker.py
- substra/sdk/backends/local/dal.py
- substra/sdk/backends/local/models.py
- substra/sdk/backends/remote/backend.py
- substra/sdk/client.py
- substra/sdk/exceptions.py
- substra/sdk/models.py
- substra/sdk/schemas.py
- tests/datastore.py
- tests/sdk/local/test_debug.py
- tests/sdk/test_download.py
- tests/sdk/test_list.py
- https://github.com/Substra/substra-backend/pull/509
- https://github.com/Substra/substra-tests/pull/256
- https://github.com/Substra/substrafl/pull/129
Modify substra to not rely on `asset` / `value` in Input assets and output assets.
Fixes FL-652
Ci in `substra` companion PR
> feat: deprecate input output

- CHANGELOG.md
- substra/sdk/client.py
- substra/sdk/exceptions.py
- tests/sdk/test_wait.py
- https://github.com/Substra/substra/pull/368
- https://github.com/Substra/substrafl/pull/147
- https://github.com/Substra/substra-tests/pull/263
- https://github.com/Substra/substra-documentation/pull/327
Centralize `wait_task` and `wait_compute_plan`, and re-use the implementation added in `substra` through the other components.
Fixes FL-1052
> feat: add `_wait`, `wait_task` and `wait_compute_plan` on `substra.Client`

- CHANGELOG.md
- setup.py
- https://github.com/Substra/substrafl/pull/148
Pin `pydantic` to `>=1.9.0` & `<2.0.0` as `pydantic` v `2.0.0` has been released with a lot of non backward compatible changes.
Fixes FL-1070
> fix: pin `pydantic` to `>=1.9.0` & `<2.0.0`

- CHANGELOG.md
- substra/sdk/backends/remote/backend.py
- tests/datastore.py
- tests/sdk/test_get.py
- https://github.com/Substra/substra-backend/pull/690
- https://github.com/Substra/substra-frontend/pull/222
Remove pagination in performance endpoints, as we always need all of them. 
Note: alternative implementation would be to iterate on all pages in `<task_id>/perf/` in all case,  in the frontend and in the SDK.
Fixes FL-1092
> fix: remove pagination on `<task_id>/perf`

- CHANGELOG.md
- substra/sdk/client.py
- tests/sdk/test_client.py
Allow to set-up configuration file path with `SUBSTRA_CLIENTS_CONFIGURATION_FILE_PATH`
Fixes FL-1063
> feat: allow config file by env var

- CHANGELOG.md
- substra/sdk/backends/local/backend.py
- substra/sdk/backends/local/compute/worker.py
- substra/sdk/backends/local/dal.py
- substra/sdk/backends/remote/backend.py
- substra/sdk/client.py
> feat: wait for compute plan & tasks to finish before using output assets

- CHANGELOG.md
- substra/sdk/exceptions.py
- tests/sdk/test_rest_client.py
Companion PR to https://github.com/Substra/substra-backend/pull/705
> chore: look for "detail" instead of "message" in API responses

- CHANGELOG.md
- substra/sdk/backends/base.py
- substra/sdk/backends/local/backend.py
- substra/sdk/backends/local/dal.py
- substra/sdk/backends/remote/backend.py
- substra/sdk/backends/remote/rest_client.py
- substra/sdk/client.py
- tests/sdk/test_client.py
Add a `Client.logout` function, which deletes a token obtained by `Client.login` (if any).
Add a context manager, making the following snippet legal:
```python
with Client(
client_name="org-1",
backend_type="remote",
url="http://substra-backend.org-1.com:8000",
username="org-1",
password="p@sswr0d44",
) as client:
pass
```
Requires https://github.com/Substra/substra-backend/pull/698
Closes FL-1008
> feat: add Client.logout and context manager

- substra/sdk/backends/remote/rest_client.py
- substra/sdk/exceptions.py
`Client.logout` is called in `__del__` and raising exceptions there is discouraged, therefore this PR removes that.
See Sarah's comment: https://github.com/Substra/substra/pull/381#discussion_r1297021646
> fix: prevent Client.logout from raising exceptions

- CHANGELOG.md
- substra/sdk/backends/remote/rest_client.py
- tests/sdk/test_rest_client.py
Currently instantiating a Client with `insecure=True` (which disables SSL verification) will still fail you at login if you have an invalid TLS certificate. This fixes that.
> fix: make Client(insecure=True) affect login & logout

- CHANGELOG.md
- substra/sdk/backends/local/dal.py
- substra/sdk/backends/remote/backend.py
> fix: convert round_idx metadata to int in Performances

- CHANGELOG.md
- tests/data_factory.py
- https://github.com/Substra/substra-tools/pull/86 (main)
- https://github.com/Substra/substra-tests/pull/284
- https://github.com/owkin/substra-ci/pull/129
- https://github.com/Substra/substra-backend/pull/736
- https://github.com/Substra/substra/pull/389
> chore: remove minimal and workflow substra-tools images

- .github/workflows/python.yml
- CHANGELOG.md
- setup.py
- tests/data_factory.py
- https://github.com/Substra/substra-tools/pull/85 (main)
- https://github.com/Substra/substrafl/pull/169
- https://github.com/Substra/substra/pull/388
- https://github.com/Substra/substra-tests/pull/283
- https://github.com/Substra/substra-documentation/pull/367
- https://github.com/owkin/substra-ci/pull/127
- https://github.com/owkin/substra-generator/pull/136
> chore: add python 3.11 support

- CHANGELOG.md
- substra/sdk/models.py
- substra/sdk/schemas.py
- tests/sdk/test_schemas.py
See slack https://owkin.slack.com/archives/C01UWGW68N8/p1696943277910689 for context
closes FL-1243
Resolve `path` and `paths` on datasample spec.
> feat: resolve relative datasample spec path

- CHANGELOG.md
- references/sdk.md
- references/sdk_models.md
- setup.py
- substra/sdk/backends/local/backend.py
- substra/sdk/backends/local/compute/spawner/subprocess.py
- substra/sdk/backends/local/compute/worker.py
- substra/sdk/backends/local/dal.py
- substra/sdk/client.py
- substra/sdk/models.py
- tests/data_factory.py
- tests/datastore.py
- tests/sdk/test_rest_client.py
Companion PRs
https://github.com/Substra/orchestrator/pull/310
https://github.com/Substra/substra-backend/pull/739
> feat!: rename function to archive

- CHANGELOG.md
- substra/sdk/backends/remote/backend.py
Companion PR https://github.com/Substra/substra-backend/pull/824
Fixes FL-1285
> feat: update download_logs url

- CHANGELOG.md
- references/sdk.md
- references/sdk_models.md
- substra/sdk/backends/local/backend.py
- substra/sdk/backends/local/compute/worker.py
- substra/sdk/backends/local/dal.py
- substra/sdk/client.py
- substra/sdk/models.py
- tests/datastore.py
- tests/sdk/test_wait.py
- tests/test_utils.py
> feat!: Add Function status

- references/sdk.md
- references/sdk_models.md
- substra/sdk/client.py
> fix: wait_function

- substra/sdk/schemas.py
- tests/sdk/test_schemas.py
> chore: check not None path on datasamplespec

- substra/sdk/assets.py
> chore: remove unused assets.py file

- .github/workflows/publish.yml
> chore: publish on pypi with hatch

- .github/workflows/publish.yml
- .github/workflows/python.yml
- tests/sdk/test_client.py
> chore: bump actions using node 16 to node 20

- changes/417.changed
- references/sdk_schemas.md
- substra/sdk/schemas.py
- tests/sdk/test_schemas.py
closes FL-1513
Create an "empty" description file if none given:
> chore: descritpion.md are now optional

- substra/sdk/schemas.py
- substra/sdk/utils.py
> feat: add optional followlinks to datasamples spec

- .github/workflows/python.yml
https://github.com/Substra/substra/actions/runs/10825863599/job/30038921156
> fix(workflows/python): deprecated actions/upload-artifact@v2 

- .github/workflows/python.yml
- changes/428.removed
- pyproject.toml
- substra/sdk/backends/local/compute/worker.py
> chore: drop Python 3.9 support
