Substra/substra

tests/test_cli.py

Removing the tempfile module in tests/test_cli.py

Remove the tempfile module

---

examples/compute_plan/scripts/display_scores.py
examples/cross_val/scripts/cross_val_algo_random_forest.py
examples/titanic/assets/algo_random_forest/algo.py
examples/titanic/scripts/add_dataset_objective.py
examples/titanic/scripts/add_train_algo_random_forest.py

A few of the examples files were not compliant with our flake8 rules, they are now.

Run flake8 through the examples

---

references/cli.md
references/sdk.md
substra/cli/interface.py
substra/sdk/client.py

Permissions doc update

---

.github/CODEOWNERS

This PR updates the list of codeowners as discussed some time ago with the new orga.

update codeowners according to new orga

---

README.md
docs/README.md
docs/add_data_samples.md
docs/ingest_data.md
references/sdk.md
substra/sdk/client.py

improve documentation for add_data_sample

---

docs/local_install.md

Fix minor typo in local_install.md

Claire phi/fix minor typo

---

tests/datastore.py

Related issue: #11 
Replace permissions' names in datastore.py with camelcases

Add camelcases to permissions - Issue #11

---

references/cli.md
substra/cli/interface.py
tests/test_cli.py

Related issue: #6 
Adding an optional parameter named in_models_keys

Add in model keys to add_traintuple - Issue #6

---

docs/local_install.md

Use the public docker.io image registry to pull substra-tools.

[Doc] Update docker image registry address.

---

substra/cli/interface.py
substra/cli/printers.py

Add the --profile option in the commands suggested by the printers
See #28

Add profile option in suggested commands - Issue #28

---

references/cli.md
references/sdk.md
substra/cli/interface.py
substra/cli/printers.py
substra/sdk/assets.py
substra/sdk/client.py
tests/datastore.py
tests/sdk/test_add.py
tests/sdk/test_describe.py
tests/sdk/test_download.py
tests/sdk/test_get.py
tests/sdk/test_list.py
tests/test_cli.py

_____________
Associated PRs:
- [backend](https://github.com/SubstraFoundation/substra-backend/pull/40)
- [chaincode](https://github.com/SubstraFoundation/substra-chaincode/pull/26)
- [tools](https://github.com/SubstraFoundation/substra-tools/pull/9)

Add aggregate algo & traintuple

---

docs/local_install_skaffold.md

Manual update is suggested if both the initial way and the way using bash do not work.

Update command to update /etc/host via bash.

---

examples/compute_plan/scripts/display_scores.py
references/cli.md
references/sdk.md
substra/cli/interface.py
substra/cli/printers.py
substra/sdk/assets.py
substra/sdk/client.py
tests/datastore.py
tests/sdk/test_add.py
tests/sdk/test_describe.py
tests/sdk/test_download.py
tests/sdk/test_get.py
tests/sdk/test_list.py
tests/test_cli.py

_____________
Associated PRs:
- [backend](https://github.com/SubstraFoundation/substra-backend/pull/13)
- [chaincode](https://github.com/SubstraFoundation/substra-chaincode/pull/5)
- [tools](https://github.com/SubstraFoundation/substra-tools/pull/3)

Implement methods related to composite algo and composite traintuple

---

references/sdk.md
substra/sdk/client.py

Doc: add missing fields

---

substra/cli/printers.py

The list testtuple command contained a typo.

Fix compute plan printer

---

docs/local_install_skaffold.md

Fix links to code archives in local install with skaffold guide

---

references/sdk.md
substra/sdk/client.py
substra/sdk/rest_client.py
tests/sdk/test_rest_client.py

- timeout is now an input parameter of the Client class to avoid setting
- retry on timeout is now enabled by default (this is required to handle TimeoutLedger errors)

fix retry timeout

---

references/cli.md
substra/cli/interface.py
substra/sdk/client.py
substra/sdk/rest_client.py
substra/sdk/user.py

- add debug/info log when receiving / finishing high level Client methods
- add debug log when doing an HTTP request
- remove unecessary debug log for configuration

Improve loggings

---

examples/compute_plan/assets/algo_sgd/Dockerfile
examples/titanic/assets/algo_constant/Dockerfile
examples/titanic/assets/algo_random_forest/Dockerfile
examples/titanic/assets/objective/Dockerfile

Bump version from 0.2.0 to 0.4.0

Update substra-tools image version

---

tests/datastore.py
tests/sdk/test_add.py
tests/sdk/test_list.py
tests/test_cli.py

For now, some commands are not tested at all.
This PR aims to add the missing tests.

Add missing tests

---

references/sdk.md
substra/cli/interface.py
substra/sdk/client.py
tests/datastore.py

Fix #93.
Update documentation with expected field.
Companion PRs:
- [backend](https://github.com/SubstraFoundation/substra-backend/pull/133)
- [tests](https://github.com/SubstraFoundation/substra-tests/pull/66)

Fix: dataset can be linked with only one objective

---

references/sdk.md
substra/sdk/client.py

Companion PR to https://github.com/SubstraFoundation/substra-chaincode/pull/110
⚠️ This branch is based on #144

Fix doc for testtuple's AlreadyExists exception

---

references/sdk.md
substra/cli/printers.py
substra/sdk/client.py

Companion PR https://github.com/SubstraFoundation/substra-backend/pull/172

Add clean model and tag option in the documentation

---

references/cli.md
substra/cli/interface.py

Fixes #48 
Replace options --pretty/--yaml/--json with a unique -o / --output option.

Common output option

---

substra/sdk/client.py

See companion PR https://github.com/SubstraFoundation/substra-backend/pull/228 for more details.

Send data as json

---

examples/titanic/README.md

Specify that you have to checkout the repository and where to run commands from.

Update titanic readme

---

bin/generate_cli_documentation.py
examples/compute_plan/scripts/add_compute_plan.py
examples/titanic/scripts/add_dataset_objective.py
examples/titanic/scripts/add_train_algo_constant.py
examples/titanic/scripts/add_train_algo_random_forest.py
tests/sdk/conftest.py

Add permissions to ALGO, DATASET & OBJECTIVE
Fix #167

Fix titanic example add_dataset_objective

---

references/sdk.md
substra/sdk/client.py

Fix doc typo

---

references/cli.md
references/sdk.md
substra/cli/interface.py
substra/sdk/client.py
tests/datastore.py

🔗 **Related PRs:**
- [substra-tests](https://github.com/SubstraFoundation/substra-tests/pull/90)
- [substra-chaincode](https://github.com/SubstraFoundation/substra-chaincode/pull/111)
- [substra-backend](https://github.com/SubstraFoundation/substra-backend/pull/186)
- [substra-frontend (coming soon)](#)
The goal of these PRs is to add a `metadata` field in every asset in order to be able to store information related to this asset. It could be, for instance, a creation_ts, an epoch, a project_name, ...

Add user metadata

---

substra/cli/printers.py

This PR aims to add the metadata field in the get command's output.

Add metadata in get command's output

---

examples/titanic/scripts/requirements.txt

Add substratools the titanic requirements

---

examples/compute_plan/assets/algo_sgd/Dockerfile
examples/titanic/assets/algo_constant/Dockerfile
examples/titanic/assets/algo_random_forest/Dockerfile
examples/titanic/assets/dataset/opener.py
examples/titanic/assets/objective/Dockerfile
examples/titanic/scripts/requirements.txt
references/cli.md
references/sdk.md
substra/cli/interface.py
substra/runner.py

https://github.com/SubstraFoundation/substra-tools/pull/38

Add n_samples argument for fake data

---

substra/__version__.py

Support new objects and methods in the local backend:
- aggregate tuples
- composite traintuples
- create a compute plan directly with the add_compute_plan and update_compute_plan methods

bump version to 0.7.0-alpha.1

---

substra/sdk/backends/local/backend.py

Reviews and comments to improve the code on the debugging.
- `def list(self, asset_type, filters=None):`

Review and comments on the debugging

---

docs/README.md

Update urls in `/docs/README.md` & remove docker-compose setup

Fix docs urls

---

examples/compute_plan/scripts/add_compute_plan.py
examples/compute_plan/scripts/display_scores.py
references/sdk.md
substra/cli/printers.py
substra/sdk/backends/local/backend.py
substra/sdk/backends/local/dal.py
substra/sdk/backends/local/models.py
substra/sdk/backends/remote/backend.py
substra/sdk/client.py
substra/sdk/exceptions.py
tests/datastore.py
tests/test_cli.py

The backend responses should be more consistent. The goal of this PR is to make sure that all inputs fields and response fields of backend endpoints are in snake_case format.
PRs:
https://github.com/SubstraFoundation/substra-backend/pull/315
https://github.com/SubstraFoundation/substra/pull/222
https://github.com/SubstraFoundation/substra-tests/pull/142

Switch from camel case to snake case

---

substra/sdk/backends/remote/rest_client.py
substra/sdk/utils.py
tests/sdk/test_list.py

Companion PR : 
https://github.com/SubstraFoundation/substra-backend/pull/316
https://github.com/SubstraFoundation/substra-frontend/pull/81

Remove nested list in api results

---

examples/compute_plan/assets/algo_sgd/Dockerfile
examples/titanic/assets/algo_constant/Dockerfile
examples/titanic/assets/algo_random_forest/Dockerfile
examples/titanic/assets/objective/Dockerfile
substra/sdk/backends/local/compute/worker.py

This PR is extracted from https://github.com/SubstraFoundation/substra/pull/236/files

fix data samples order in local env

---

.github/workflows/python.yml
substra/sdk/backends/local/compute/spawner.py

Support [Docker rootless](https://docs.docker.com/engine/security/rootless/) and updated the CI to test that (I assumed if it runs on rootless, it runs in normal mode, so in the CI it runs only in rootless mode).

feat: support Docker rootless

---

.github/workflows/publish.yml
.github/workflows/python.yml
tests/data_factory.py

ci: fix the CI to use the public repos

---

CHANGELOG.md
substra/sdk/backends/local/compute/spawner/base.py
substra/sdk/backends/local/compute/spawner/docker.py
substra/sdk/backends/local/compute/spawner/subprocess.py
substra/sdk/backends/local/compute/worker.py
tests/sdk/test_subprocess.py

Companion PRs:
- https://github.com/Substra/substra-tools/pull/55 (main PR)
- https://github.com/Substra/substra/pull/279 (this PR)
- https://github.com/Substra/substra-backend/pull/473
---
This fixes a bug when the substra-tools command line argument list is too long.

fix: pass arguments to substra-tools via a file

---

CHANGELOG.md
tests/data_factory.py
tests/fl_interface.py

Use `datasamples` as input identifiers for X and y accros all functions. 
Pass `rank` within a new argument named `task_properties`
Companion PRs: 
- substra: (here) https://github.com/Substra/substra/pull/284
- substrafl https://github.com/Substra/substrafl/pull/20
- substra-tests: https://github.com/Substra/substra-tests/pull/207
- substra-tools (main) https://github.com/Substra/substra-tools/pull/58
- substra-documentation: https://github.com/Substra/substra-documentation/pull/179

feat: uniformized inputs and outputs accross functions

---

CHANGELOG.md
substra/sdk/backends/local/compute/worker.py
tests/data_factory.py

https://github.com/Substra/substra-tools/pull/60

feat: update following the metric change in substratools

---

docs/README.md
references/cli.md
references/sdk.md
substra/cli/interface.py

Replace SubstraFoundation links with Substra

docs: fix links

---

tests/data_factory.py

fix: substratools image

---

CHANGELOG.md
tests/data_factory.py
tests/test_cli.py

- https://github.com/Substra/substra-tools/pull/65 (MAIN)
- https://github.com/Substra/substra/pull/310
- https://github.com/Substra/substrafl/pull/37
- https://github.com/Substra/substra-documentation/pull/202
- https://github.com/Substra/substra-tests/pull/225

test: register substratools function with decorator

---

references/sdk.md
substra/sdk/client.py

fix: link_dataset_with_data_samples and client docstrings 

---

.github/workflows/python.yml
CHANGELOG.md
Makefile
setup.py

fix: remove depreciated pytest-runner

---

CHANGELOG.md
substra/sdk/backends/local/compute/spawner/docker.py

fix: windows compatibility

---

.github/workflows/python.yml
CHANGELOG.md

Signed-off-by: Guilhem Barthes <guilhem.barthes@owkin.com>
Fix cgroups errors in some tests using Docker in Docker.

fix: python GA on ubuntu 20.04 for docker rootless compatibility

---

CHANGELOG.md
substra/sdk/backends/local/compute/worker.py

- https://github.com/Substra/substra-backend/pull/548 (main)
- https://github.com/Substra/substra-tools/pull/75
- https://github.com/Substra/substra/pull/329
Asana card https://app.asana.com/0/1202209633046022/1203021914361542/f

chore: rank in task properties

---

references/sdk.md
substra/sdk/backends/remote/backend.py
substra/sdk/client.py
tests/sdk/local/test_debug.py

docs: correct from_config_file docstring

---

CHANGELOG.md
substra/sdk/backends/local/backend.py
substra/sdk/models.py
substra/sdk/schemas.py
tests/conftest.py
tests/data_factory.py
tests/datastore.py
tests/sdk/local/test_debug.py

- https://github.com/Substra/substra/pull/332 - MAIN
- https://github.com/Substra/substra-backend/pull/551
- https://github.com/Substra/substra-documentation/pull/246
- https://github.com/Substra/substrafl/pull/67
- https://github.com/Substra/substra-tests/pull/235
- https://github.com/Substra/orchestrator/pull/116
https://app.asana.com/0/1202209633046022/1203074394111393/f

feat!: remove test only for Datasamples

---

README.md

Update test instructions in the README

docs: update test instructions in the README

---

.github/CODEOWNERS

chore: change code owners

---

CHANGELOG.md
bin/generate_sdk_schemas_documentation.py
references/sdk.md
references/sdk_models.md
references/sdk_schemas.md
substra/sdk/backends/base.py
substra/sdk/backends/local/backend.py
substra/sdk/backends/local/compute/spawner/docker.py
substra/sdk/backends/local/compute/spawner/subprocess.py
substra/sdk/backends/local/dal.py
substra/sdk/backends/remote/backend.py
substra/sdk/client.py
substra/sdk/compute_plan.py
substra/sdk/models.py
substra/sdk/schemas.py
tests/data_factory.py
tests/datastore.py
tests/fl_interface.py
tests/sdk/local/test_debug.py
tests/sdk/test_download.py
tests/sdk/test_get.py
tests/sdk/test_list.py
tests/sdk/test_rest_client.py
tests/sdk/test_update.py

https://app.asana.com/0/1203124674173179/1203842723899063/f
- https://github.com/Substra/substra-tests/pull/239
- https://github.com/Substra/substra/pull/337
- https://github.com/Substra/substrafl/pull/79
- 
- https://github.com/owkin/substra-ci/actions/runs/4044324704

chore!: rename tuples to tasks

---

substra/sdk/archive/tarsafe.py
substra/sdk/backends/local/backend.py
substra/sdk/backends/local/compute/spawner/subprocess.py
substra/sdk/backends/local/compute/worker.py
substra/sdk/backends/remote/backend.py
substra/sdk/graph.py

Signed-off-by: SdgJlbl <sarah.diot-girard@owkin.com>
Linting in failing due to upgrade of `black` to 23.1.0
Apparently `black` is now allergic to blank lines 🤷

chore: fix files following black upgrade to 23.1.0

---

setup.py

Improve pypi page: https://pypi.org/project/substra/

docs: update setup.py description and URL

---

substra/sdk/client.py
tests/sdk/test_client.py

Follow-up to https://github.com/Substra/substra/pull/353 😑

fix: fix login check in substra client config

---

CHANGELOG.md
substra/sdk/backends/local/dal.py
substra/sdk/backends/remote/backend.py
substra/sdk/models.py
tests/datastore.py

Remove metric from the performance data model
- https://github.com/Substra/substra-backend/pull/650
- https://github.com/Substra/orchestrator/pull/213 (main)
- https://github.com/Substra/substra/pull/358

chore: remove metric from performance

---

setup.py

fix: pin urllib3 version

---

CHANGELOG.md
substra/sdk/utils.py

fix: typo in exception

---

bin/generate_sdk_schemas_documentation.py
references/sdk.md
references/sdk_schemas.md

doc: add ComputeTaskOutputSpec doc

---

bin/generate_sdk_schemas_documentation.py
references/sdk_models.md
references/sdk_schemas.md

Remove private class `_File` from documentation.

chore: update documentation

---

pyproject.toml

chore: add README.md to pyproject.toml

---

changes/413.added
substra/sdk/client.py

chore: add warning in hybrid mode

---

changes/415.changed
pyproject.toml

chore: exclude requests 2.32.*

---

pyproject.toml

chore: match dependency syntax with substrafl
